version: "3"
services:
  ftcregtest:
    build: ./ftc-in-a-box
    stdin_open: true
    tty: true
    command: /bin/bash -c "cd /data && make start && /bin/bash"
  explorer:
    build: ./explorer
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
    links:
      - mongodb
      - ftcregtest
    depends_on:
      - mongodb
      - ftcregtest
    command: /bin/bash -c "cd /opt/iquidus && npm start"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet